---
title: "Mini-Project 2"
author: "Kim Zhang, Emily Raphael, Maddie Haines"
date: "October 31, 2017"
output: html_document
---
## Loading the data

```{r, include=FALSE}

load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
```


put tables in a useable format
```{r, warning = FALSE, include = FALSE}

#filtered house_elections
house_filtered <- house_elections %>%
  select(fec_id, general_votes, ge_winner)
house_filtered

#filtered candidates
candidates_filtered <- candidates %>% 
   select(-c(cand_st1, cand_st2, cand_city, cand_state,cand_zip))
candidates_filtered

#filtered contributions
contributions_filtered <- contributions %>% 
  select(cmte_id, name, city, state, zip_code, transaction_dt, transaction_amt, cand_id, other_id)
contributions_filtered

 #filter committees 
committees_filtered <- committees %>% 
  select(cmte_id, cmte_name, cmte_city, cmte_state, cmte_zip, cmte_party_affiliation, cand_id)
committees_filtered
```

merge the nice tables
```{r, warning = FALSE, include = FALSE}

house_filtered2 <- house_filtered %>%
  rename(cand_id = fec_id)

house_filtered2

joined_table <- 
  left_join(candidates_filtered, house_filtered2, by = "cand_id")
complete_table <- left_join(joined_table, contributions_filtered, by = "cand_id")

complete_table
```
```{r}
c <- complete_table %>%
  select(cand_office_state, cand_election_yr, cand_office_state) %>%
  distinct(cand_office_state)
c


kimtest <- complete_table %>%
  filter(cand_election_yr == "2012", cand_office == "S") 

new <- distinct(kimtest, cand_office_state) %>%
  .$cand_office_state
new
```

```{r}
#lubridate
require(lubridate)

dates <- complete_table %>% 
  mutate(date = mdy(transaction_dt))
glimpse(dates)
```

view the new table
```{r}
# sorting the complete table

presum_races <- dates %>%
  filter(cand_election_yr == "2012", cand_office == "S")%>%  
  group_by(cand_name, transaction_dt) %>%
  mutate(total = sum(transaction_amt))
presum_races
```


```{r}

kim <- function(state) {
  
 monthly <- presum_races %>%
    filter(cand_office_state == state ) %>%
    filter(date >= "2012-01-01")

 by_month2 <- monthly %>% 
  mutate(month = format(date, "%m"), year = format(date, "%Y")) %>%
  group_by(cand_id, month, year)%>%
  mutate(monthly_contr = sum(transaction_amt))
 
 by_month3 <-by_month2%>%
   mutate(M = as.integer(month))
 
   find_total <- by_month3 %>% 
      group_by(cand_id)%>%
      summarise(totalz = sum(abs(transaction_amt)))%>%
      arrange(desc(totalz)) %>%
      mutate( id = row_number())%>% 
      filter(id <= 3)
   find_total
   
top3table <- left_join(by_month3, find_total, by = "cand_id")
top3table

#is this join correct? if left does the state go away?? 



#gotta put the state variable using filter(cand_office_state == state)

candidate1 <- top3table %>% 
  filter(id == 1) %>%
  mutate(id1 = as.factor(id)) %>%
  mutate( M = as.integer(month))

candidate2 <- top3table %>%
  filter(id == 2)%>%
  mutate(id1 = as.factor(id)) %>%
  mutate( M = as.integer(month))

candidate3 <- top3table %>% 
  filter(id == 3) %>%
  mutate(id1 = as.factor(id))%>%
  mutate( M = as.integer(month))

plotz <- 
  ggplot(top3table, aes(x = M, y = monthly_contr)) +  
  geom_point(data = candidate2, aes(x = M, y = monthly_contr, color = id1)) + 
  geom_point(data = candidate1, aes(x = M, y = monthly_contr, color = id1)) +
  geom_point(data = candidate3, aes(x = M, y = monthly_contr, color = id1)) + 
  geom_line(data = candidate1, aes(x = M, y = monthly_contr, color =id1)) +
  geom_line(data = candidate2, aes(x = M, y = monthly_contr, color = id1)) + 
  geom_line(data = candidate3, aes(x = M, y = monthly_contr, color = id1)) 
  #ggtitle()

plotz
}
```